/**
 * 389. Find the Difference
Easy

2549

371

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 */
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
 var findTheDifference = function(s, t) {
    let map = new Map();
    for (const ch of s) {
        if (map.has (ch)) {
            map.set (ch, map.get (ch) + 1);
        } else {
            map.set (ch, 1);
        }
    }
    for (const ch of t) {
        if (!map.has (ch) || map.get (ch) == 0) {
            return ch;
        }
        map.set (ch, map.get (ch) - 1);
    }
    return '0';
};